# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:        Splendid
subtitle:     Stay Hungry Stay Foolish
description:  This is Fangzheng Zou’s personal blog.
keywords:     mainpage
language:     "zh" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:      "" # the subpath of your site, e.g. /blog
url:          http://zoufangzheng.com # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:    /blog/:categories/:title
cover:        /assets/mountain-cover.jpg

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
comments :
  provider : duoshuo
  duoshuo :
    short_name : zou1995